### ISSUE TITLE
Numpy 1.24 breaks builtin type aliases

### ISSUE THREAD

**Issue by marvinvanaalst** [osqp/osqp-python#104]
The numpy people marked aliases of builtin types like `np.int` as deprecated in version [1.20.0](https://numpy.org/doc/stable/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated). They are effectively deprecated with version [1.24.0](https://numpy.org/devdocs/release/1.24.0-notes.html#expired-deprecations) which was just released.

This leads to a bunch of `AttributeError`s, like 

```python
AttributeError: module 'numpy' has no attribute 'int'
```
Your `requirements.txt` states compatability for `numpy >=1.7` and thus causes CI to crash on this (but that's on the numpy folks).

The corresponding pull request is #105 .

This issue is related to [cobra issue 1305](https://github.com/opencobra/cobrapy/issues/1305)

**Comment by vineetbansal** [comment]
v0.6.2.post9 fixes this.Thanks for bringing this to our attention!
