### ISSUE TITLE
Support for building python3.13 wheels

### ISSUE THREAD

**Issue by Transurgeon** [osqp/osqp-python#161]
Hello, cvxpy is in the process of adding wheels for python 3.13 (see [here](https://github.com/cvxpy/cvxpy/pull/2577)).
However, there seems to be a compatibility issue with installing osqp (see the CI logs or the comments in the PR).
I was wondering if it would be possible to help setup osqp wheels that support python 3.13 (this issue may be related to the conda-recipe of OSQP?). 

Please let me know if there is anything I can help with.

**Comment by imciner2** [comment]
The OSQP PyPi wheels now have a Python 3.13 version.
