### ISSUE TITLE
Hard to install on Python 3.10 due to missing qdldl wheels

### ISSUE THREAD

**Issue by cdiener** [osqp/osqp-python#68]
Even though osqp has wheels for Python 3.10 it depends on qdldl which does not.

**Comment by vineetbansal** [comment]
@imciner2 - looks like the python wrappers are using `import qdldl` directly at:
https://github.com/osqp/osqp-python/blob/696e1a11b92f8e1ed67551c7c42710ff2cba1f75/src/osqp/interface.py#L14

This has to do with the investigations into the derivative that are also currently part of the `master` branch. See:
https://github.com/osqp/osqp-python/blob/696e1a11b92f8e1ed67551c7c42710ff2cba1f75/src/osqp/interface.py#L388

Thus we have a dependency on `qdldl` defined in our `pyproject.toml`.
Perhaps we can disable this derivative calculation in `master` for now (and it's associated unit test)?

In any case, on python 3.10, at least on Linux, `pip` is able to compile the `qdldl` wheel to produce `qdldl-0.1.5.post0-cp310-cp310-linux_x86_64.whl` which is usable, indicating it may not be a big deal to support python 3.10 wheels for `qdldl` after all - I feel like that may be an easy and the proper solution here.

**Comment by vineetbansal** [comment]
Hi @cdiener - we've now released python 3.10 wheels for `qdldl` on pypi (for linux/mac/windows), and will continue to do so for any future releases. I'm closing this issue, but feel free to open it in case I missed something.

**Comment by cdiener** [comment]
Awesome, thank you!
